# Generated by Django 4.2.4 on 2023-08-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='TechData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=30)),
                ('op_number', models.CharField(max_length=20)),
                ('op_name', models.CharField(max_length=200)),
                ('ws_name', models.CharField(max_length=100)),
                ('op_name_full', models.CharField(max_length=255)),
                ('ws_number', models.CharField(max_length=10)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('is_planned', models.BooleanField(default=False)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tehnolog.productcategory')),
            ],
            options={
                'db_table': 'tech_data',
            },
        ),
    ]
