# Generated by Django 4.2.4 on 2024-03-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Категория изделия',
                'verbose_name_plural': 'Категории изделий',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='TechData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=30)),
                ('op_number', models.CharField(max_length=20)),
                ('op_name', models.CharField(max_length=200)),
                ('ws_name', models.CharField(max_length=100)),
                ('op_name_full', models.CharField(max_length=255)),
                ('ws_number', models.CharField(max_length=10)),
                ('norm_tech', models.FloatField(blank=True, null=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('draw_path', models.CharField(blank=True, max_length=255, null=True)),
                ('draw_filename', models.TextField(blank=True, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tehnolog.productcategory')),
            ],
            options={
                'verbose_name': 'Технологические данные',
                'verbose_name_plural': 'Технологические данные',
                'db_table': 'tech_data',
            },
        ),
    ]
