# Generated by Django 4.2.4 on 2023-08-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehnolog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория изделия', 'verbose_name_plural': 'Категории изделий'},
        ),
        migrations.AlterModelOptions(
            name='techdata',
            options={'verbose_name': 'Технологические данные', 'verbose_name_plural': 'Технологические данные'},
        ),
    ]
