# Generated by Django 4.2.4 on 2023-08-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnolog', '0002_alter_productcategory_options_alter_techdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='techdata',
            name='norm_tech',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
