# Generated by Django 4.2.4 on 2023-08-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehnolog', '0002_productmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techdata',
            name='is_planned',
        ),
    ]
