# Generated by Django 4.2.4 on 2023-09-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehnolog', '0003_remove_techdata_is_planned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
