# Generated by Django 4.2.4 on 2023-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnolog', '0003_techdata_norm_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techdata',
            name='norm_tech',
            field=models.FloatField(null=True),
        ),
    ]
