# Generated by Django 4.2.4 on 2023-09-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnolog', '0004_delete_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='techdata',
            name='draw_filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techdata',
            name='draw_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
