# Generated by Django 4.2.4 on 2023-09-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnolog', '0005_techdata_draw_filename_techdata_draw_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techdata',
            name='draw_filename',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='techdata',
            name='draw_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
