# Generated by Django 4.2.4 on 2023-08-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.PositiveSmallIntegerField()),
                ('model_name', models.CharField(db_index=True, max_length=30)),
                ('datetime_done', models.DateTimeField()),
                ('op_number', models.CharField(max_length=20)),
                ('op_name', models.CharField(max_length=200)),
                ('ws_name', models.CharField(max_length=100)),
                ('op_name_full', models.CharField(max_length=255)),
                ('ws_number', models.CharField(max_length=10)),
                ('norm_tech', models.FloatField(blank=True, null=True)),
                ('datetime_techdata_create', models.DateTimeField()),
                ('datetime_techdata_update', models.DateTimeField()),
                ('is_planned', models.BooleanField(default=False)),
                ('order', models.CharField(max_length=30)),
                ('datetime_plan_ws', models.DateTimeField(auto_now=True)),
                ('datetime_plan_wp', models.DateTimeField(null=True)),
                ('datetime_assign_wp', models.DateTimeField(null=True)),
                ('datetime_job_start', models.DateTimeField(null=True)),
                ('datetime_master_call', models.DateTimeField(null=True)),
                ('datetime_otk_call', models.DateTimeField(null=True)),
                ('datetime_otk_answer', models.DateTimeField(null=True)),
                ('master_calls', models.IntegerField(null=True)),
                ('norm_fact', models.FloatField(null=True)),
                ('otk_decision', models.CharField(max_length=30, null=True)),
                ('decision_time', models.DateTimeField(null=True)),
                ('st_status', models.CharField(default='не запланировано', max_length=15)),
                ('otk_answer', models.CharField(max_length=30, null=True)),
                ('master_finish_wp', models.CharField(max_length=30, null=True)),
                ('dispatcher_plan_ws', models.CharField(max_length=30, null=True)),
                ('dispatcher_plan_wp', models.CharField(max_length=30, null=True)),
                ('master_assign_wp', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Технологические данные',
                'verbose_name_plural': 'Технологические данные',
                'db_table': 'shift_task',
            },
        ),
        migrations.CreateModel(
            name='WorkshopSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.PositiveSmallIntegerField()),
                ('model_name', models.CharField(max_length=30)),
                ('datetime_done', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'График цеха',
                'verbose_name_plural': 'График цеха',
                'db_table': 'workshop_schedule',
            },
        ),
    ]
