# Generated by Django 4.2.4 on 2023-11-15 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doers', models.CharField(max_length=255, unique=True, verbose_name='ФИО исполнителей')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'db_table': 'doers',
            },
        ),
        migrations.CreateModel(
            name='WorkshopSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.PositiveSmallIntegerField(null=True, verbose_name='Цех')),
                ('model_name', models.CharField(max_length=30, verbose_name='Модель изделия')),
                ('datetime_done', models.DateField(null=True, verbose_name='Планируемая дата готовности')),
                ('order', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('order_status', models.CharField(default='не запланировано', max_length=20, verbose_name='Статус заказа')),
                ('model_order_query', models.CharField(max_length=60, null=True, unique=True, verbose_name='заказ и модель')),
                ('query_prior', models.PositiveSmallIntegerField(default=1, verbose_name='Приоритет заявки чертежей')),
                ('done_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='процент готовности')),
                ('td_status', models.CharField(default='запрошено', max_length=20, verbose_name='Статус технической документации')),
                ('td_query_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата/время запроса документации')),
                ('td_remarks', models.TextField(blank=True, verbose_name='замечания к КД')),
                ('tehnolog_remark_fio', models.CharField(max_length=30, null=True, verbose_name='Замечание от')),
                ('is_remark', models.BooleanField(default=False, null=True, verbose_name='Факт наличия замечания к КД')),
                ('remark_datetime', models.DateTimeField(null=True, verbose_name='дата/время замечания к КД')),
                ('td_const_done_datetime', models.DateTimeField(null=True, verbose_name='дата/время ответа конструктора по КД')),
                ('td_tehnolog_done_datetime', models.DateTimeField(null=True, verbose_name='дата/время ответа технолога по КД')),
                ('plan_datetime', models.DateTimeField(null=True, verbose_name='дата/время выполнения планирования заказа')),
                ('dispatcher_query_td_fio', models.CharField(max_length=30, null=True, verbose_name='Запросил КД')),
                ('dispatcher_plan_ws_fio', models.CharField(max_length=31, null=True, verbose_name='Запланировал')),
                ('constructor_query_td_fio', models.CharField(max_length=30, null=True, verbose_name='Передал КД')),
                ('tehnolog_query_td_fio', models.CharField(max_length=30, null=True, verbose_name='Утвердил / загрузил')),
                ('product_category', models.CharField(max_length=30, null=True, verbose_name='Категория изделия')),
            ],
            options={
                'verbose_name': 'График цеха',
                'verbose_name_plural': 'График цеха',
                'db_table': 'workshop_schedule',
            },
        ),
        migrations.CreateModel(
            name='ShiftTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.PositiveSmallIntegerField(null=True, verbose_name='Цех')),
                ('model_name', models.CharField(db_index=True, max_length=30, verbose_name='Модель изделия')),
                ('datetime_done', models.DateField(null=True, verbose_name='Ожидаемая дата готовности')),
                ('order', models.CharField(max_length=100, null=True, verbose_name='Номер заказа')),
                ('model_order_query', models.CharField(max_length=60, null=True, verbose_name='заказ и модель')),
                ('op_number', models.CharField(max_length=20, verbose_name='Номер операции')),
                ('op_name', models.CharField(max_length=200, verbose_name='Имя операции')),
                ('ws_name', models.CharField(max_length=100, verbose_name='Имя рабочего центра')),
                ('op_name_full', models.CharField(max_length=255, verbose_name='Полное имея операции')),
                ('ws_number', models.CharField(max_length=10, verbose_name='Номер рабочего центра')),
                ('norm_tech', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Технологическая норма времени')),
                ('datetime_techdata_create', models.DateTimeField(auto_now_add=True, verbose_name='дата/время занесения технологических данных')),
                ('datetime_techdata_update', models.DateTimeField(auto_now=True, verbose_name='дата/время корректировки технологических данных')),
                ('datetime_plan_ws', models.DateTimeField(auto_now=True, verbose_name='время планирования в цех')),
                ('datetime_plan_wp', models.DateTimeField(null=True, verbose_name='время планирования РЦ')),
                ('fio_doer', models.CharField(default='не распределено', max_length=255, null=True, verbose_name='ФИО исполнителей')),
                ('datetime_assign_wp', models.DateTimeField(null=True, verbose_name='время распределения')),
                ('datetime_job_start', models.DateTimeField(null=True, verbose_name='время начала работ')),
                ('datetime_master_call', models.DateTimeField(null=True, verbose_name='время вызова мастера')),
                ('master_finish_wp', models.CharField(max_length=30, null=True, verbose_name='ФИО мастера вызова ОТК')),
                ('datetime_otk_call', models.DateTimeField(null=True, verbose_name='время вызова ОТК')),
                ('datetime_otk_answer', models.DateTimeField(null=True, verbose_name='время ответа ОТК')),
                ('master_calls', models.IntegerField(default=0, null=True, verbose_name='количество вызовов мастера')),
                ('master_called', models.CharField(default='не было', max_length=10, null=True, verbose_name='статус вызова мастера')),
                ('norm_fact', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Фактическая норма времени')),
                ('otk_answer', models.CharField(max_length=30, null=True, verbose_name='ФИО контролёра ответа ОТК')),
                ('otk_decision', models.CharField(max_length=30, null=True, verbose_name='ФИО контролёра решения ОТК')),
                ('decision_time', models.DateTimeField(null=True, verbose_name='Время приёмки ОТК')),
                ('st_status', models.CharField(default='не запланировано', max_length=20, verbose_name='Статус СЗ')),
                ('is_fail', models.BooleanField(default=False, null=True, verbose_name='Факт наличия брака')),
                ('datetime_fail', models.DateTimeField(null=True, verbose_name='Время регистрации брака')),
                ('fio_failer', models.CharField(max_length=255, null=True, verbose_name='ФИО бракоделов')),
                ('master_assign_wp_fio', models.CharField(max_length=30, null=True, verbose_name='Распределил')),
                ('excel_list_name', models.CharField(max_length=100, null=True, verbose_name='Лист excel технологического процесса')),
                ('draw_path', models.CharField(blank=True, max_length=254, null=True, verbose_name='путь к связанным чертежам')),
                ('draw_filename', models.TextField(blank=True, null=True, verbose_name='имя чертежа')),
                ('product_category', models.CharField(null=True, verbose_name='Категория изделия')),

            ],
            options={
                'verbose_name': 'Сменное задание',
                'verbose_name_plural': 'Сменные задания',
                'db_table': 'shift_task',
            }
            ,
        ),
        migrations.AddField(
            model_name='shifttask',
            name='datetime_job_resume',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время возобновления работы'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='job_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность работы'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='next_shift_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='previous_shift_task', to='scheduler.shifttask',
                                    verbose_name='Новое СЗ на исправление брака'),
        ),
    ]
