# Generated by Django 4.2.4 on 2024-03-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='doers_tech',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество исполнителей по ТД'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='norm_calc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True, verbose_name='Расчетная норма времени'),
        ),
    ]
