# Generated by Django 4.2.4 on 2023-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttask',
            name='is_planned',
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='order',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='order_status',
            field=models.CharField(default='запланировано', max_length=20),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='order',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='st_status',
            field=models.CharField(default='не запланировано', max_length=20),
        ),
    ]
