# Generated by Django 4.2.4 on 2023-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_shifttask_is_planned_workshopschedule_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopschedule',
            name='datetime_done',
            field=models.DateField(),
        ),
    ]
