# Generated by Django 4.2.4 on 2024-04-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_shifttask_doers_tech_shifttask_norm_calc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttask',
            name='op_name',
            field=models.TextField(verbose_name='Имя операции'),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='op_name_full',
            field=models.TextField(verbose_name='Полное имея операции'),
        ),
    ]
