# Generated by Django 4.2.4 on 2024-02-12 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_shifttask_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Не подтверждено', max_length=254, verbose_name='Статус')),
                ('reason', models.CharField(max_length=50, verbose_name='Причина')),
                ('description', models.CharField(default='', max_length=254, verbose_name='Описание')),
                ('datetime_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('datetime_start', models.DateTimeField(blank=True, null=True, verbose_name='Время начала простоя')),
                ('datetime_end', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания простоя')),
                ('master_decision_fio', models.CharField(blank=True, max_length=30, null=True, verbose_name='ФИО мастера')),
                ('shift_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='scheduler.shifttask', verbose_name='СЗ')),
            ],
            options={
                'verbose_name': 'Простой',
                'verbose_name_plural': 'Простои',
                'db_table': 'downtime',
            },
        ),
    ]
