# Generated by Django 4.2.4 on 2024-06-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_modelparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelparameters',
            name='critical_chain_cycle_koef',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=10, null=True, verbose_name='Коэффициент расчёта критической цепи'),
        ),
        migrations.AlterField(
            model_name='modelparameters',
            name='day_hours_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Часов в день на изделие'),
        ),
        migrations.AlterField(
            model_name='modelparameters',
            name='difficulty_koef',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Коэффициент сложности изделия'),
        ),
        migrations.AlterField(
            model_name='modelparameters',
            name='produce_cycle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Производственный цикл'),
        ),
    ]
