# Generated by Django 4.2.4 on 2023-08-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_workshopschedule_datetime_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttask',
            name='datetime_done',
            field=models.DateField(),
        ),
    ]
