# Generated by Django 4.2.4 on 2024-02-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='datetime_decision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время решения'),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='status',
            field=models.CharField(default='не подтверждено', max_length=254, verbose_name='Статус'),
        ),
    ]
