# Generated by Django 4.2.4 on 2024-06-21 10:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_modelparameters_critical_chain_cycle_koef_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(verbose_name='Название серии изделий')),
                ('cycle_polynom_koef', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=10, max_digits=12, null=True), null=True, size=None, verbose_name='Коэффициенты формулы расчёта критической цепи по массе')),
                ('difficulty_koef', models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Коэффициент сложности изделия')),
            ],
            options={
                'verbose_name': 'Параметры серии',
                'verbose_name_plural': 'Параметры серии',
                'db_table': 'series_parameters',
            },
        ),
        migrations.RemoveField(
            model_name='modelparameters',
            name='cycle_polynom_koef',
        ),
        migrations.RemoveField(
            model_name='modelparameters',
            name='difficulty_koef',
        ),
        migrations.AddField(
            model_name='modelparameters',
            name='series_parameters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.seriesparameters', verbose_name='Параметры серии'),
        ),
    ]
