# Generated by Django 4.2.4 on 2024-07-01 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_seriesparameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doers',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрен'),
        ),
        migrations.AddField(
            model_name='doers',
            name='telegram_id',
            field=models.BigIntegerField(default=0, null=True, verbose_name='telegram_id исполнителя'),
        ),
        migrations.AlterField(
            model_name='modelparameters',
            name='series_parameters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduler.seriesparameters', verbose_name='Параметры серии'),
        ),
    ]
