# Generated by Django 4.2.4 on 2023-08-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_shifttask_datetime_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='fio_doer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
