# Generated by Django 4.2.4 on 2023-08-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_shifttask_fio_doer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttask',
            name='fio_doer',
            field=models.CharField(default='Не распределено', max_length=255, null=True),
        ),
    ]
