# Generated by Django 4.2.4 on 2024-07-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_doers_is_approved_doers_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doers',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
    ]
