# Generated by Django 4.2.4 on 2024-07-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_doers_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopschedule',
            name='calculated_datetime_done',
            field=models.DateField(null=True, verbose_name='Расчётная дата готовности'),
        ),
    ]
