# Generated by Django 4.2.4 on 2023-08-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_shifttask_fio_doer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doers', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'db_table': 'doers',
            },
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='fio_doer',
            field=models.CharField(default='не распределено', max_length=255, null=True),
        ),
    ]
