# Generated by Django 4.2.4 on 2024-07-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_workshopschedule_calculated_datetime_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopschedule',
            name='calculated_datetime_done',
            field=models.DateField(default=models.DateField(null=True, verbose_name='Планируемая дата готовности'), null=True, verbose_name='Расчётная дата готовности'),
        ),
    ]
