# Generated by Django 4.2.4 on 2024-07-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_workshopschedule_calculated_datetime_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopschedule',
            name='calculated_datetime_done',
        ),
    ]
