# Generated by Django 4.2.4 on 2023-08-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_doers_doers'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='master_called',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='master_calls',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
