# Generated by Django 4.2.4 on 2024-07-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_remove_workshopschedule_calculated_datetime_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopschedule',
            name='calculated_datetime_done',
            field=models.DateField(null=True, verbose_name='Расчётная дата готовности'),
        ),
    ]
