# Generated by Django 4.2.4 on 2024-07-18 06:59
# Миграция для копирования значений datetime_done в calculated_datetime_done после создания
from django.db import migrations
class Migration(migrations.Migration):

    def copy_existing_to_new(apps, schema_editor):
        MyModel = apps.get_model('scheduler', 'WorkshopSchedule')
        for row in MyModel.objects.all():
            row.calculated_datetime_done = row.datetime_done
            row.save()

    dependencies = [
        ('scheduler', '0010_workshopschedule_calculated_datetime_done'),
    ]

    operations = [
        migrations.RunPython(copy_existing_to_new),
    ]
