# Generated by Django 4.2.4 on 2023-08-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_shifttask_master_called'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttask',
            name='master_called',
        ),
    ]
