# Generated by Django 4.2.4 on 2024-07-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_auto_20240718_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopschedule',
            name='td_status',
            field=models.CharField(default='запрошено', max_length=20, null=True, verbose_name='Статус технической документации'),
        ),
    ]
