# Generated by Django 4.2.4 on 2023-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_shifttask_master_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttask',
            name='norm_fact',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='norm_tech',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
