# Generated by Django 4.2.4 on 2024-07-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_workshopschedule_produce_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopschedule',
            name='contract_end_date',
            field=models.DateField(null=True, verbose_name='Дата готовности по договору'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='contract_start_date',
            field=models.DateField(null=True, verbose_name='Дата начала по договору'),
        ),
    ]
