# Generated by Django 4.2.4 on 2023-09-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_alter_shifttask_norm_fact_alter_shifttask_norm_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='datetime_fail',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='fio_failer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='is_fail',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
