# Generated by Django 4.2.4 on 2023-09-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_shifttask_datetime_fail_shifttask_fio_failer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttask',
            name='master_called',
            field=models.CharField(default='не было', max_length=10, null=True),
        ),
    ]
