# Generated by Django 4.2.4 on 2023-09-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_alter_shifttask_master_called'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='plan_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='td_const_done_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='td_query_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='td_status',
            field=models.CharField(default='запрошено', max_length=20),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='td_tehnolog_done_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workshopschedule',
            name='order_status',
            field=models.CharField(default='не запланировано', max_length=20),
        ),
    ]
