# Generated by Django 4.2.4 on 2024-08-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_workshopschedule_calculated_datetime_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopschedule',
            name='late_days',
            field=models.IntegerField(default=0, null=True, verbose_name='отставание дней'),
        ),
    ]
