# Generated by Django 4.2.4 on 2023-09-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_workshopschedule_model_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocQuery',
        ),
        migrations.AlterField(
            model_name='workshopschedule',
            name='datetime_done',
            field=models.DateField(null=True),
        ),
    ]
