# Generated by Django 4.2.4 on 2023-09-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_delete_docquery_alter_workshopschedule_datetime_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopschedule',
            name='done_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
