# Generated by Django 4.2.4 on 2023-09-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tehnolog', '0006_alter_techdata_draw_filename_and_more'),
        ('scheduler', '0021_alter_shifttask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата/время добавления данных в таблицу'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата/время обновления данных таблицы'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='draw_filename',
            field=models.TextField(blank=True, null=True, verbose_name='имя чертежа'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='draw_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='путь к связанным чертежам'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tehnolog.productcategory', verbose_name='Категория изделия'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='constructor_query_td_fio',
            field=models.CharField(max_length=30, null=True, verbose_name='Передал КД'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='is_remark',
            field=models.BooleanField(default=False, null=True, verbose_name='Факт наличия замечания к КД'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='query_prior',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Приоритет заявки чертежей'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='remark_datetime',
            field=models.DateTimeField(null=True, verbose_name='дата/время замечания к КД'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='td_remarks',
            field=models.TextField(blank=True, verbose_name='замечания к КД'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='tehnolog_excel_load_fio',
            field=models.CharField(max_length=30, null=True, verbose_name='Загрузил'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='tehnolog_query_td_fio',
            field=models.CharField(max_length=30, null=True, verbose_name='Утвердил'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='tehnolog_remark_fio',
            field=models.CharField(max_length=30, null=True, verbose_name='Замечание от'),
        ),
        migrations.AlterField(
            model_name='workshopschedule',
            name='model_query',
            field=models.CharField(max_length=60, null=True, verbose_name='заказ и модель'),
        ),
    ]
