# Generated by Django 4.2.4 on 2023-10-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_shifttask_datetime_create_shifttask_datetime_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshopschedule',
            old_name='model_query',
            new_name='model_order_query',
        ),
    ]
