# Generated by Django 4.2.4 on 2023-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_shifttask_model_order_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttask',
            name='workshop',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Цех'),
        ),
    ]
