# Generated by Django 4.2.4 on 2023-10-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0027_alter_shifttask_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttask',
            name='datetime_done',
            field=models.DateField(null=True, verbose_name='Ожидаемая дата готовности'),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='order',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер заказа'),
        ),
    ]
