# Generated by Django 4.2.4 on 2023-10-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_remove_shifttask_datetime_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopschedule',
            name='model_order_query',
            field=models.CharField(max_length=60, null=True, verbose_name='заказ и модель'),
        ),
    ]
