# Generated by Django 4.2.4 on 2023-10-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0032_shifttask_excel_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopschedule',
            name='tehnolog_excel_load_fio',
        ),
        migrations.AlterField(
            model_name='workshopschedule',
            name='tehnolog_query_td_fio',
            field=models.CharField(max_length=30, null=True, verbose_name='Утвердил / загрузил'),
        ),
    ]
