# Generated by Django 4.2.4 on 2023-10-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0033_remove_workshopschedule_tehnolog_excel_load_fio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopschedule',
            name='product_category',
            field=models.CharField(null=True, verbose_name='Категория изделия'),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='product_category',
            field=models.CharField(null=True, verbose_name='Категория изделия'),
        ),
    ]
