# Generated by Django 4.2.4 on 2023-11-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0034_workshopschedule_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttask',
            options={'verbose_name': 'Сменное задание', 'verbose_name_plural': 'Сменные задания'},
        ),
        migrations.AddField(
            model_name='shifttask',
            name='datetime_job_resume',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время возобновления работы'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='job_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность работы'),
        ),
        migrations.AddField(
            model_name='shifttask',
            name='next_shift_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_shift_task', to='scheduler.shifttask', verbose_name='Новое СЗ на исправление брака'),
        ),
        migrations.AlterField(
            model_name='workshopschedule',
            name='product_category',
            field=models.CharField(max_length=30, null=True, verbose_name='Категория изделия'),
        ),
    ]
