# Generated by Django 4.2.4 on 2023-11-20 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0035_alter_shifttask_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_plan', models.DateField(verbose_name='Месяц планирования')),
                ('month_plan_amount', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='План на месяц в н/ч')),
            ],
            options={
                'verbose_name': 'Ежедневный отчёт',
                'verbose_name_plural': 'Ежедневные отчёты',
                'db_table': 'month_plan_table',
            },
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='model_name',
            field=models.CharField(db_index=True, max_length=30, validators=[django.core.validators.RegexValidator(message="Имя модели может содержать только цифры и буквы латинского алфавита и знак '-' тире", regex='^[\\-A-Za-z0-9]+$')], verbose_name='Модель изделия'),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='order',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Имя заказа может содержать только цифры, буквы, знаки тире "-" и скобки "()"', regex='^[А-Яа-яA-Za-z0-9\\(\\)\\-]+$')], verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='workshopschedule',
            name='model_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Имя модели может содержать только цифры и буквы латинского алфавита и знак '-' тире", regex='^[\\-A-Za-z0-9]+$')], verbose_name='Модель изделия'),
        ),
        migrations.AlterField(
            model_name='workshopschedule',
            name='order',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Имя заказа может содержать только цифры, буквы, знаки тире "-" и скобки "()"', regex='^[А-Яа-яA-Za-z0-9\\(\\)\\-]+$')], verbose_name='Номер заказа'),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_day', models.DateField(verbose_name='Дата отчёта')),
                ('day_plan', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='План на день')),
                ('day_fact', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Факт за день')),
                ('plan_sum', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Всего план на дату')),
                ('fact_sum', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Всего факт на дату')),
                ('plan_done_rate', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='% выполнения плана')),
                ('fact_done_rate', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Фактический % выполнения плана')),
                ('plan_loos', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Отставание/опережение плана')),
                ('day_fails', models.PositiveSmallIntegerField(verbose_name='Случаев брака за день')),
                ('day_save_violations', models.PositiveSmallIntegerField(verbose_name='Случаев нарушений ОТПБ за день')),
                ('personal_total_c1', models.PositiveSmallIntegerField(verbose_name='Всего персонала в цехе 1')),
                ('personal_shift_c1', models.PositiveSmallIntegerField(verbose_name='Выход в дату персонала в цехе 1')),
                ('personal_total_welders_c1', models.PositiveSmallIntegerField(verbose_name='Всего сварщиков в цехе 1')),
                ('personal_shift_welders_c1', models.PositiveSmallIntegerField(verbose_name='Выход в дату сварщиков в цехе 1')),
                ('personal_total_locksmiths_c1', models.PositiveSmallIntegerField(verbose_name='Всего слесарей в цехе 1')),
                ('personal_shift_locksmiths_c1', models.PositiveSmallIntegerField(verbose_name='Выход в дату слесарей в цехе 1')),
                ('month_plan_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='month_plan_table', to='scheduler.monthplans', verbose_name='Месяц планирования')),
            ],
            options={
                'verbose_name': 'Ежедневный отчёт',
                'verbose_name_plural': 'Ежедневные отчёты',
                'db_table': 'report',
            },
        ),
    ]
