# Generated by Django 4.2.4 on 2023-11-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0036_monthplans_alter_shifttask_model_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthplans',
            options={'verbose_name': 'План на месяц в н/ч', 'verbose_name_plural': 'Планы на месяц в н/ч'},
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='day_plan_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Факт за день'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='day_fact',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Факт за день'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='day_fails',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Случаев брака за день'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='day_plan',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='План на день'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='day_save_violations',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Случаев нарушений ОТПБ за день'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='fact_done_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Фактический % выполнения плана'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='fact_sum',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Всего факт на дату'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='personal_shift_c1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Выход в дату персонала в цехе 1'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='personal_shift_locksmiths_c1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Выход в дату слесарей в цехе 1'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='personal_shift_welders_c1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Выход в дату сварщиков в цехе 1'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='personal_total_c1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Всего персонала в цехе 1'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='personal_total_locksmiths_c1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Всего слесарей в цехе 1'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='personal_total_welders_c1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Всего сварщиков в цехе 1'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='plan_done_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='% выполнения плана'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='plan_loos',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Отставание/опережение плана'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='plan_sum',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Всего план на дату'),
        ),
    ]
