# Generated by Django 4.2.4 on 2023-11-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0037_alter_monthplans_options_dailyreport_day_plan_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthplans',
            name='workshop',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Цех'),
        ),
    ]
