# Generated by Django 4.2.4 on 2023-11-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0038_monthplans_workshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='personal_shift_c1',
            new_name='personal_shift',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='personal_shift_locksmiths_c1',
            new_name='personal_shift_locksmiths',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='personal_shift_welders_c1',
            new_name='personal_shift_welders',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='personal_total_c1',
            new_name='personal_total',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='personal_total_locksmiths_c1',
            new_name='personal_total_locksmiths',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='personal_total_welders_c1',
            new_name='personal_total_welders',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='workshop',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='monthplans',
            name='workshop',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Цех'),
        ),
    ]
