# Generated by Django 4.2.4 on 2023-11-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0039_rename_personal_shift_c1_dailyreport_personal_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='plan_loos',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='plan_loos_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Отставание/опережение плана'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='day_plan_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% выполнения плана за день'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='fact_done_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фактический % выполнения плана'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='plan_done_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% выполнения плана'),
        ),
    ]
