# Generated by Django 4.2.4 on 2023-11-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0040_remove_dailyreport_plan_loos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='aver_fact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Отставание/опережение плана'),
        ),
    ]
