# Generated by Django 4.2.4 on 2023-11-29 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0040_remove_dailyreport_plan_loos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='workpiece',
            field=models.JSONField(blank=True, null=True, verbose_name='Заготовка'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='datetime_sz',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата заявки'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='product_name',
            field=models.CharField(blank=True, null=True, verbose_name='Номер СЗ заявителя'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='sz_need_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата потребности'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='sz_number',
            field=models.CharField(blank=True, null=True, verbose_name='Номер СЗ заявителя'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='month_plan_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_plan_table', to='scheduler.monthplans', verbose_name='Месяц планирования'),
        ),
    ]
