# Generated by Django 4.2.4 on 2023-12-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0042_dailyreport_personal_night_locksmiths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='workpiece',
            field=models.JSONField(blank=True, null=True, verbose_name='Заготовка'),
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='sz',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные служебной записки'),
        ),
    ]
