# Generated by Django 4.2.4 on 2023-11-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0042_workshopschedule_sz_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopschedule',
            name='datetime_sz',
        ),
        migrations.RemoveField(
            model_name='workshopschedule',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='workshopschedule',
            name='sz_author',
        ),
        migrations.RemoveField(
            model_name='workshopschedule',
            name='sz_need_date',
        ),
        migrations.RemoveField(
            model_name='workshopschedule',
            name='sz_number',
        ),
        migrations.AddField(
            model_name='workshopschedule',
            name='sz',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные служебной записки'),
        ),
    ]
