# Generated by Django 4.2.4 on 2023-12-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('scheduler', '0042_dailyreport_personal_night_locksmiths_and_more'),
        ('scheduler', '0043_shifttask_workpiece_workshopschedule_sz'),
    ]

    operations = [
        migrations.AddField(
            model_name='doers',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
