# Generated by Django 4.2.4 on 2023-12-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0044_doers_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='fio_tehnolog',
            field=models.CharField(blank=True, default='не распределено', max_length=255, null=True, verbose_name='ФИО технолога'),
        ),
    ]
