# Generated by Django 4.2.4 on 2023-12-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0045_shifttask_fio_tehnolog_shifttask_workpiece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttask',
            name='plasma_layout',
            field=models.CharField(blank=True, default='Не выполнена', max_length=255, null=True, verbose_name='Раскладка'),
        ),
    ]
