# Generated by Django 4.2.4 on 2023-12-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0046_shifttask_plasma_layout_shifttask_workpiece_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='shifttask',
            name='workshop_plasma',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цех плазмы'),
        ),

    ]
