# Generated by Django 4.2.4 on 2023-12-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0047_shifttask_workpiece_shifttask_workshop_plasma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doers',
            name='ws_plasma',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цех плазмы (по умолчанию)'),
        ),

    ]
