# Generated by Django 4.2.4 on 2024-01-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0048_doers_ws_plasma_shifttask_workpiece_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task2Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='shifttask',
            name='tech_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id в техпроцессе'),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='next_shift_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_shift_task', to='scheduler.shifttask', verbose_name='Новое СЗ'),
        ),
        migrations.AlterField(
            model_name='shifttask',
            name='norm_tech',
            field=models.DecimalField(decimal_places=5, max_digits=13, null=True, verbose_name='Технологическая норма времени'),
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.DeleteModel(
            name='MonthPlans',
        ),
        migrations.AddField(
            model_name='task2task',
            name='next',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='scheduler.shifttask'),
        ),
        migrations.AddField(
            model_name='task2task',
            name='previous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='scheduler.shifttask'),
        ),
    ]
