# Generated by Django 4.2.4 on 2024-06-10 05:31

from django.db import migrations
from orders.models import Materials


def populate_materials(apps, schema_editor):
    Materials = apps.get_model("orders", "Materials")
    Materials.objects.create(name="Материалы не требуются")


def populate_shops(apps, schema_editor):
    Shops = apps.get_model("orders", "Shops")
    Shops.objects.create(name="Цех № 1")
    Shops.objects.create(name="Цех № 2")
    Shops.objects.create(name="Цех № 3")
    Shops.objects.create(name="Цех № 4")
    Shops.objects.create(name="Цех № 5")


def populate_status(apps, schema_editor):
    OrderStatus = apps.get_model("orders", "OrderStatus")
    OrderStatus.objects.create(name="требует ремонта")
    OrderStatus.objects.create(name="ремонт начат")
    OrderStatus.objects.create(name="требуются материалы")
    OrderStatus.objects.create(name="ожидание акта")
    OrderStatus.objects.create(name="в ремонте")
    OrderStatus.objects.create(name="ремонт окончен")
    OrderStatus.objects.create(name="ремонт принят")
    OrderStatus.objects.create(name="ремонт отменен")
    OrderStatus.objects.create(name="неремонтопригодно")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_materials),
        migrations.RunPython(populate_shops),
        migrations.RunPython(populate_status),
    ]
