# Generated by Django 4.2.4 on 2024-06-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_auto_20240610_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.shops",
                verbose_name="Местонахождение",
            ),
        ),
    ]
