# Generated by Django 4.2.4 on 2024-06-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_equipment_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="worker",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Работник"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="identified_employee",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Работник, создавший заявку"
            ),
        ),
        migrations.AlterField(
            model_name="shops",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Местонахождение"
            ),
        ),
    ]
