# Generated by Django 4.2.4 on 2024-06-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_repairmen_active_alter_repairmen_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'Материалы', 'verbose_name_plural': 'Материалы'},
        ),
    ]
