# Generated by Django 4.2.4 on 2024-06-27 12:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_materials_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdersWorkers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.orders"
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.repairmen",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orders",
            name="dayworkers",
            field=models.ManyToManyField(through="orders.OrdersWorkers", to="orders.repairmen"),
        ),
    ]
