# Generated by Django 4.2.4 on 2024-07-01 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_equipment_ppr_plan_day_ordersworkers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="doers_fio",
        ),
        migrations.AlterField(
            model_name="orders",
            name="dayworkers",
            field=models.ManyToManyField(
                related_name="orders",
                through="orders.OrdersWorkers",
                to="orders.repairmen",
            ),
        ),
        migrations.AlterField(
            model_name="ordersworkers",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.orders"
            ),
        ),
        migrations.AlterField(
            model_name="ordersworkers",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.repairmen"
            ),
        ),
    ]
