# Generated by Django 4.2.4 on 2024-07-01 08:01

from django.db import migrations, models
import django.db.models.deletion
import orders.utils.common


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_remove_orders_doers_fio_equipment_ppr_plan_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="previous_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_with_previous_status",
                to="orders.orderstatus",
                verbose_name="Предыдущий статус",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.ForeignKey(
                default=orders.utils.common.OrdStatus["DETECTED"],
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_with_status",
                to="orders.orderstatus",
                verbose_name="Статус заявки",
            ),
        ),
    ]
