# Generated by Django 4.2.4 on 2024-07-02 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_equipment_ppr_plan_day_orders_previous_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordersworkers",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="orders.orders",
            ),
        ),
        migrations.AlterField(
            model_name="ordersworkers",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="orders.repairmen",
            ),
        ),
    ]
