# Generated by Django 4.2.4 on 2024-07-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_equipment_ppr_plan_day_alter_ordersworkers_order_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ordersworkers",
            unique_together={("worker", "order", "start_date")},
        ),
    ]
