# Generated by Django 4.2.4 on 2024-07-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_equipment_ppr_plan_day_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ordersworkers",
            unique_together=set(),
        ),
    ]
