# Generated by Django 4.2.4 on 2024-07-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_ordersworkers_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="material_request_file",
            field=models.FileField(
                null=True, upload_to="", verbose_name="Скан заявки на материалы"
            ),
        ),
    ]
