# Generated by Django 4.2.4 on 2024-07-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_equipment_ppr_plan_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="in_operation",
            field=models.BooleanField(default=True, verbose_name="В эксплуатации"),
        ),
    ]
