# Generated by Django 4.2.4 on 2024-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_equipment_in_operation_equipment_ppr_plan_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="is_ppr",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Заявка на ППР"),
        ),
    ]
