# Generated by Django 4.2.4 on 2024-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_equipment_ppr_plan_day_orders_is_ppr"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="ppr_plan_day",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="День планового ремонта",
            ),
        ),
    ]
