# Generated by Django 4.2.4 on 2024-07-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_alter_orders_breakdown_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="acceptance_date",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Дата закрытия заявки"
            ),
        ),
        migrations.AlterField(
            model_name="ordersworkers",
            name="end_date",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
