# Generated by Django 4.2.4 on 2024-07-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_alter_orders_acceptance_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="dayworkers_fio",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Ремонтники"
            ),
        ),
        migrations.CreateModel(
            name="WorkersLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dayworkers_fio",
                    models.CharField(max_length=256, verbose_name="Ремонтники"),
                ),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers_log",
                        to="orders.orders",
                    ),
                ),
            ],
        ),
    ]
