# Generated by Django 4.2.4 on 2024-07-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0023_orders_dayworkers_fio_workerslog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="dayworkers_fio",
            new_name="dayworkers_string",
        ),
        migrations.RenameField(
            model_name="workerslog",
            old_name="dayworkers_fio",
            new_name="dayworkers_string",
        ),
    ]
