# Generated by Django 4.2.4 on 2024-07-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_rename_dayworkers_fio_orders_dayworkers_string_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="dayworkers",
        ),
        migrations.DeleteModel(
            name="OrdersWorkers",
        ),
    ]
