# Generated by Django 4.2.4 on 2024-07-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_remove_orders_dayworkers_delete_ordersworkers"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="make_ppr_order",
            field=models.BooleanField(
                default=True, verbose_name="Формировать заявки ППР каждый месяц"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="in_operation",
            field=models.BooleanField(
                default=True, verbose_name="Находится эксплуатации"
            ),
        ),
    ]
