# Generated by Django 4.2.4 on 2024-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_equipment_make_ppr_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "sheetname",
                    models.CharField(max_length=255, verbose_name="Имя листа"),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
            ],
        ),
    ]
