# Generated by Django 4.2.4 on 2024-07-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_referencematerials"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencematerials",
            name="original_name",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Оригинальное название листа"
            ),
            preserve_default=False,
        ),
    ]
