# Generated by Django 4.2.4 on 2024-08-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencematerials",
            name="original_name",
            field=models.CharField(
                max_length=255, verbose_name="Оригинальное название листа"
            ),
        ),
    ]
