# Generated by Django 4.2.4 on 2024-08-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduler", "0018_workshopschedule_late_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectAct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_fail", models.DateTimeField(verbose_name="Дата")),
                (
                    "tech_number",
                    models.IntegerField(
                        db_index=True, verbose_name="Технический номер акта"
                    ),
                ),
                (
                    "act_number",
                    models.CharField(max_length=60, unique=True, verbose_name="№ Акта"),
                ),
                (
                    "workshop",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Цех"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Операция"
                    ),
                ),
                (
                    "processing_object",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Объект"
                    ),
                ),
                (
                    "control_object",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Объект контроля",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="количество"
                    ),
                ),
                (
                    "inconsistencies",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Выявленные несоответствия",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "tech_service",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Тех. служба",
                    ),
                ),
                (
                    "tech_solution",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Тех. решение",
                    ),
                ),
                (
                    "fixable",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="брак исправимый"
                    ),
                ),
                (
                    "fio_failer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "fixing_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Время исправления"
                    ),
                ),
                (
                    "cause",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXC", "ошибка исполнителя"),
                            ("TEC", "ошибка технолога"),
                            ("CON", "ошибка конструктора"),
                            ("MAT", "брак материала"),
                        ],
                        max_length=4,
                        null=True,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "master_finish_wp",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Ответственный мастер",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, verbose_name="Заполнены все необходимые поля"
                    ),
                ),
                (
                    "media_ref",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Папка с файлами"
                    ),
                ),
                (
                    "media_count",
                    models.IntegerField(
                        default=0, verbose_name="количество файлов в папке"
                    ),
                ),
                (
                    "shift_task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.shifttask",
                        verbose_name="Ссылка на сменное задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акт о браке",
                "verbose_name_plural": "Акты о браке",
                "ordering": ["tech_number"],
            },
        ),
    ]
