# Generated by Django 4.2.4 on 2024-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defectact",
            name="completed",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Форма заполнена"
            ),
        ),
    ]
