# Generated by Django 4.2.4 on 2024-08-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defectact",
            name="cause",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXC", "ошибка исполнителя"),
                    ("TEC", "ошибка технолога"),
                    ("CON", "ошибка конструктора"),
                    ("MAT", "брак материала"),
                ],
                max_length=4,
                null=True,
                verbose_name="Причина",
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="completed",
            field=models.BooleanField(
                default=False, verbose_name="Заполнены все необходимые поля"
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="control_object",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Объект контроля"
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="fio_failer",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Виновник"
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="fixable",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="брак исправимый"
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="inconsistencies",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Выявленные несоответствия",
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="master_finish_wp",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Ответственный мастер",
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="operation",
            field=models.CharField(blank=True, max_length=255, verbose_name="Операция"),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="processing_object",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Объект"
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="количество"),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="remark",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Примечание"
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="tech_service",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Тех. служба"
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="tech_solution",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Тех. решение"
            ),
        ),
        migrations.AlterField(
            model_name="defectact",
            name="workshop",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Цех"
            ),
        ),
    ]
