# Generated by Django 4.2.4 on 2024-07-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defectact",
            options={
                "ordering": ["-datetime_fail"],
                "verbose_name": "Акт о браке",
                "verbose_name_plural": "Акты о браке",
            },
        ),
        migrations.AddField(
            model_name="defectact",
            name="media_count",
            field=models.IntegerField(
                default=0, verbose_name="количество файлов в папке"
            ),
        ),
    ]
