from django.urls import path
from .views import (
    equipment,
    orders,
    EquipmentCardView,
    EquipmentCardEditView,
    order_assign_workers,
    order_finish_repair,
    order_accept_repair,
    order_revision,
    order_report,
    order_clarify_repair,
    order_confirm_materials,
    order_card,
    order_edit,
    order_history,
    order_cancel_repair,
    order_delete_proc,
    ShopsView,
    shop_delete_proc,
    shop_edit_proc,
    order_upload_pdf,
    show_pdf,
    OrdersArchive,
    RepairmenHistory,
    filter_data,
    clear_workers_proc,
    PPRСalendar, reference_matreials, convert_excel, ShowReference, reference_delete_proc,
)

urlpatterns = [
    path("equipment/", equipment, name="equipment"),
    path("equipment/<int:equipment_id>/", EquipmentCardView.as_view(), name="equipment_card"),
    path(
        "equipment_edit/<int:equipment_id>/",
        EquipmentCardEditView.as_view(),
        name="equipment_card_edit",
    ),
    path("start_repair/<int:pk>", order_assign_workers, name="start_repair"),
    path("clarify_repair/<int:pk>", order_clarify_repair, name="clarify_repair"),
    path("confirm_materials/<int:pk>", order_confirm_materials, name="confirm_materials"),
    path("finish_repair/<int:pk>", order_finish_repair, name="finish_repair"),
    path("accept_repair/<int:pk>", order_accept_repair, name="accept_repair"),
    path("revision_repair/<int:pk>", order_revision, name="revision_repair"),
    path("cancel_repair/<int:pk>", order_cancel_repair, name="cancel_repair"),
    path("order_info/<int:pk>", order_card, name="order_info"),
    path("orders/", orders, name="orders"),
    path("orders_report/", order_report, name="orders_report"),
    path("order_delete_proc/", order_delete_proc, name="order_delete_proc"),
    path("edit_repair/<int:pk>", order_edit, name="edit_repair"),
    path("repair_history/<int:pk>", order_history, name="repair_history"),
    path("shops/", ShopsView.as_view(), name="shops"),
    path("shop_edit/", shop_edit_proc, name="shop_edit"),
    path("shops_delete/", shop_delete_proc, name="shop_delete"),
    path("repairmen_history/<int:pk>", RepairmenHistory.as_view(), name="repairmen_history"),
    path("upload_pdf/<int:pk>", order_upload_pdf, name="upload_pdf"),
    path("show_pdf/<int:pk>", show_pdf, name="show_pdf"),
    path("orders_archive/", OrdersArchive.as_view(), name="orders_archive"),
    path("filter_data/", filter_data, name="filter_data"),
    path("clear_workers/<int:pk>", clear_workers_proc, name="clear_workers"),
    path("ppr_calendar/", PPRСalendar.as_view(), name="ppr_calendar"),
    path("reference/", reference_matreials, name="reference"),
    path("reference/<int:pk>", ShowReference.as_view(), name="show_reference"),
    path("convert_excel/", convert_excel, name="convert_excel"),
    path("ref_delete/<int:pk>", reference_delete_proc, name="reference_delete"),


]
